---
- name: Cloning ADjutant source repository for development
  become: true
  git:
    repo: "{{ adjutant_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ adjutant_dev_repos_pull }}"
    version: "{{ adjutant_source_version }}"
