---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ adjutant_services }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: adjutant_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/adjutant/"
      skip: true

- name: Set Adjutant policy file
  set_fact:
    adjutant_policy_file: "{{ adjutant_policy.results.0.stat.path | basename }}"
    adjutant_policy_file_path: "{{ adjutant_policy.results.0.stat.path }}"
  when:
    - adjutant_policy.results

- name: Check if custom {{ adjutant_custom_metrics_yaml_file }} exists
  stat:
    path: "{{ node_custom_config }}/adjutant/{{ adjutant_custom_metrics_yaml_file }}"
  delegate_to: localhost
  register: adjutant_custom_metrics_file

- name: Copying {{ adjutant_custom_metrics_yaml_file }} if it exists
  copy:
    src: "{{ node_custom_config }}/adjutant/{{ adjutant_custom_metrics_yaml_file }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ adjutant_custom_metrics_yaml_file }}"
    mode: "0660"
  become: true
  when:
    - adjutant_custom_metrics_file.stat.exists
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ adjutant_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Are we using {{ adjutant_custom_metrics_yaml_file }}?
  set_fact:
    adjutant_custom_metrics_used: "{{ adjutant_custom_metrics_file.stat.exists }}"

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ adjutant_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over adjutant.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/adjutant.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/adjutant.conf"
      - "{{ node_custom_config }}/adjutant/{{ item.key }}.conf"
      - "{{ node_custom_config }}/adjutant/{{ inventory_hostname }}/adjutant.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/adjutant.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ adjutant_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over wsgi-adjutant.conf
  vars:
    service: "{{ adjutant_services['adjutant-api'] }}"
  template:
    src: "wsgi-adjutant.conf.j2"
    dest: "{{ node_config_directory }}/adjutant-api/wsgi-adjutant.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart adjutant-api container

- name: Copying over existing policy file
  template:
    src: "{{ adjutant_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ adjutant_policy_file }}"
    mode: "0660"
  become: true
  when:
    - adjutant_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ adjutant_services }}"
  notify:
    - Restart {{ item.key }} container
