---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ adjutant_services }}"
    service_name: "{{ project_name }}"
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - adjutant_api
  register: container_facts
  
- name: Checking free port for adjutant API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ adjutant_api_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['adjutant_api'] is not defined
    - inventory_hostname in groups['adjutant-api']