---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_adjutant_auth }}"
    service_ks_register_services: "{{ adjutant_ks_services }}"
    service_ks_register_users: "{{ adjutant_ks_users }}"
    service_ks_register_roles: "{{ adjutant_ks_roles }}"
