---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_adjutant_auth }}"
    service_ks_register_services: "{{ adjutant_ks_services }}"
    service_ks_register_users: "{{ adjutant_ks_users }}"
  tags: always